[package]
name = "ethrun"
version = "0.1.0"
description = "Ethereum Blockchain backtesting tool"
authors = ["Karim Agha <karim.dev@gmail.com>"]
edition = "2018"

[dependencies]
sled = "0.34.6"
url = "2.2"
size = "0.1"
colored = "2"
chrono = "0.4.19"
structopt = "0.3"
futures = "0.3"
hex = "0.4"
trie-db = "0.11"
ethereum-types = "0.4"
futures-util = "0.3.12"
serde_json = "1.0"
filesize = "*"
kvdb = "*"
tempdir = "*"
kvdb-rocksdb = "*"
kvdb-memorydb = "*"
keccak-hash = "*"
indicatif = "*"
tiny-keccak = "1.5"
elastic-array = "0.10.2"
tokio-tungstenite = "0.13"
tokio = { version = "1.2", features = ["full"] }
rlp = { version = "0.3.0", features = ["ethereum"] }
keccak-hasher = { version = "0.15.3" }
lazy_static = "1.4.0"
derivative = "2.2"

ethcore-builtin = { path = "../../crates/vm/builtin" }
ethcore-blockchain = { path = "../../crates/ethcore/blockchain" }

ethcore = { path = "../../crates/ethcore" }
ethjson = { path = "../../crates/ethjson/" }
blooms-db = { path = "../../crates/db/blooms-db" }
common-types = { path = "../../crates/ethcore/types" }
