[package]
name = "ethrun"
version = "0.1.0"
description = "Ethereum Blockchain backtesting tool"
authors = ["Karim Agha <karim.dev@gmail.com>"]
edition = "2018"

[dependencies]
sled = "0.34.6"
colored = "2"
chrono = "0.4.19"
structopt = "0.3"
hex = "0.4"
ethereum-types = "0.4"
filesize = "*"
kvdb = "*"
indicatif = "*"
tiny-keccak = "1.5"
elastic-array = "0.10.2"
rlp = { version = "0.3.0", features = ["ethereum"] }
keccak-hasher = { version = "0.15.3" }
lazy_static = "1.4.0"
serde_json = "*"

ethcore-builtin = { path = "../../crates/vm/builtin" }
ethcore-blockchain = { path = "../../crates/ethcore/blockchain" }

vm = { path = "../../crates/vm/vm" }
evm = { path = "../../crates/vm/evm" }
wasm = { path = "../../crates/vm/wasm" }
ethcore = { path = "../../crates/ethcore" }
ethjson = { path = "../../crates/ethjson/" }
blooms-db = { path = "../../crates/db/blooms-db" }
common-types = { path = "../../crates/ethcore/types" }

[profile.release]
debug = true