[package]
name = "ethdl"
version = "1.0.0"
authors = ["Karim Agha <karim.agha@gnosis.io"]
edition = "2018"

[dependencies]
structopt = "*"
serde_json = "*"
futures = "0.3.12"
num_cpus = "1.13"
indicatif = "*"
tokio = { version = "1.2", features = ["full"]}
tokio-stream = {version = "0.1.3" }
reqwest = { version = "0.11", features = ["json"] }